---
title: "My Maps and Places"
author: "Maneesh Pandey"
date: "May 28, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

```
## Introduction
This document provides information about supporting organizations of UN with their locations on map. Secondly it proevides a markp up with rectangles showing highest density of UN supporting organisations.


```{r,echo=TRUE}

library(leaflet)
library(dplyr)
# Marking Mutilple locations on Map, as a practice session
set.seed(2018-05-30)
df<-data.frame(lat=runif(20,min=38.2,max=38.3),lng=runif(20,min=-76.6,max = -76.5))
first_map<- df%>%leaflet()%>%addTiles()%>%addMarkers()
first_map
```

```{r,echo=TRUE}
# Dynamic map with Logo and weblink of United Nations and its organizations

set.seed(2018-05-30)
UNlat_long<-data.frame(lat=c(40.7489,41.9028,51.4934,48.8503),lng=c(-73.9680,12.4964,-0.1207,2.3038))
UN_sites<-c("http://www.un.org/en/index.html", "http://www.fao.org/home/en/", "http://www.imo.org/EN/Pages/Default.aspx", "https://en.unesco.org/")

icon.ion <- makeAwesomeIcon(icon = 'home', markerColor = 'lightred')
dyn_map<- UNlat_long%>%leaflet()%>%addTiles()%>%addAwesomeMarkers(icon=icon.ion,label=c("United Nations HQ", "FAO HQ","IMO HQ","UNESCO" ),popup=UN_sites)
dyn_map
```
```{r, echo=TRUE}
# site indicating UN Headquarters in Europe
UN_EU_map<-leaflet()%>%addTiles()%>%addRectangles(lat1=40.9000,lng1=1.9500,lat2=60.500,lng2=15.9500)

UN_EU_map

```






